### ISSUE TITLE
Updates for OE-A

### ISSUE THREAD

**Issue by RobvanderDoes** [Dima73/enigma2-plugin-extensions-sundtekcontrolcenter#5]
Not really an issue as such, but this seems to be a handy way to bring this to your attention.

Until now I update the OE-A with your plugins, for which I (sometimes) need to create an ipk. Would you be so kind to create pullrequests when you change your plugins for https://github.com/oe-alliance/3rdparty-plugins please?

**Comment by Dima73** [comment]
I do not check my plugins for compatibility with OE-A.

**Comment by RobvanderDoes** [comment]
OK, then we'll leave things as they are and I'll continuo doing the updates.
