### ISSUE TITLE
Update plugin for python 3 compatibility

### ISSUE THREAD

**Issue by davesayers2014** [Dima73/enigma2-plugin-extensions-sundtekcontrolcenter#7]
Hi can the plugin be updated for python 2/3 compatibility? Thanks

**Comment by Dima73** [comment]
What image is it for?

**Comment by davesayers2014** [comment]
OpenATV 6.5 plus other images maybe changing to python 3

Edited

See this post https://www.world-of-satellite.com/showthread.php?64409-Sundtek-control-center-python-3&p=514446&viewfull=1#post514446

**Comment by sundtek** [comment]
I think it's better to create another repository for this and keep the old plugin as it is.

**Comment by sundtek** [comment]
I just had a look at a settopbox:
1. I had to comment out all the print lines in SundtekControlCenter.py (seems like the syntax changed a bit)
2. in plugin.py I had to change "import SundtekControlCenter" to "from . import SundtekControlCenter"

**Comment by davesayers2014** [comment]
https://www.world-of-satellite.com/showthread.php?64409-Sundtek-control-center-python-3&p=514990#post514990

[SundtekControlCenter.zip](https://github.com/Dima73/enigma2-plugin-extensions-sundtekcontrolcenter/files/6711696/SundtekControlCenter.zip)


Just a note that I edited version on OpenVix feeds and it looks to be a different verion date you have. VersionI edited 20200915-2

Possibly OE have missed versions

Edit I see your IPK is the same version you just have more commits since ading the IPK.

**Comment by Dima73** [comment]
https://github.com/Dima73/enigma2-plugin-extensions-sundtekcontrolcenter/commit/8f25e6fb2221bba1ce0aa39f8409d214e21c0f6b

**Comment by Dima73** [comment]
Maybe
else: # Python 2
    from urllib import urlopen
not use urllib2?

**Comment by Huevos** [comment]
Py2 uses urllib2.

**Comment by davesayers2014** [comment]
The zip should work fine on py2/3

**Comment by davesayers2014** [comment]
Crash on python 3 trying to update drivers using your ipk 

`< 22407.6496> Traceback (most recent call last):
< 22407.6497>   File "/usr/lib/enigma2/python/StartEnigma.py", line 252, in processDelay
< 22407.6504>     callback(*retval)
< 22407.6505>   File "/usr/lib/enigma2/python/Plugins/Extensions/SundtekControlCenter/SundtekControlCenter.py", line 544, in thismenuCallback
< 22407.6516>     ret and ret[1]()
< 22407.6517>   File "/usr/lib/enigma2/python/Plugins/Extensions/SundtekControlCenter/SundtekControlCenter.py", line 822, in checkdriverversion
< 22407.6529>     match = pattern.search(netdriver)
< 22407.6531> TypeError: cannot use a string pattern on a bytes-like object
< 22407.6531> [ePyObject] (CallObject(<bound method Session.processDelay of <__main__.Session object at 0xb05f6238>>,()) failed)`

**Comment by Dima73** [comment]
https://github.com/Dima73/enigma2-plugin-extensions-sundtekcontrolcenter/commit/c116fbdb93c904d06d66431ed74e25f82bafd1b1

**Comment by davesayers2014** [comment]
> [c116fbd](https://github.com/Dima73/enigma2-plugin-extensions-sundtekcontrolcenter/commit/c116fbdb93c904d06d66431ed74e25f82bafd1b1)

That seems to be working. Thanks

I'll close this issue
